- name: Set authorized key
  tags: ssh
  authorized_key:
      user: root
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set bash prompt
  shell: |
      echo 'export PS1="[\u@\H \W]\\$ "'>> ~/.bashrc

- name: install dependent packages
  import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:      
    - "{{ rpms_path }}"
    - "/etc/cni"
