- name: start docker
  service:
     name: docker
     stated: started
- name: update supervisord
  shell: "supervisorctl reread && supervisorctl update all"
- name: restart kubelet
  shell: "supervisorctl restart kubelet"
