#- name: install docker-ce-18.03.1.ce
#  notify: start docker
#  yum: 
#    name: docker-ce-18.03.1.ce
#    state: present
#    allow_downgrade: yes
#

- name: upload docker-ce-18.03.1.ce
  copy:
    src:  docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm
    dest: "{{ rpms_path }}/"

- name: install docker-ce-18.03.1.ce
  notify: start docker
  yum: 
    name: "{{ rpms_path }}/docker-ce-18.03.1.ce-1.el7.centos.x86_64.rpm"
    state: present

- name: create docker directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:      
    - "/etc/docker"

- name: upload docker daemon.json 
  notify: restart docker
  template:
    src:  daemon.json.j2
    dest: "/etc/docker/daemon.json"
